# Generated by Django 2.2.9 on 2021-02-11 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=250)),
                ('broker', models.CharField(max_length=250)),
                ('msg', models.TextField()),
                ('country_code', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Contact number must be in the format of '+123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,11}$')])),
            ],
        ),
    ]
