# Generated by Django 2.2.9 on 2021-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='email_skype',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
